[package]
name = "lnurl-kit"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Sunsi Abreu <lsunsi@pm.me>"]
description = "All you need to support LNURL and nothing more"
keywords = ["bitcoin", "lightning", "lnurl"]
repository = "https://github.com/lsunsi/lnurl-kit"
license = "GPL-3.0-only"

[dependencies]
bech32 = { version = "0.9.0", default-features = false }
serde = { version = "1.0.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0.0", features = ["std"], default-features = false }
url = { version = "2.5.0", features = ["serde"], default-features = false }
