[package]
name = "lnurl-kit"
version = "0.1.0"
edition = "2021"
authors = ["Lucas Sunsi Abreu <lsunsi@pm.me>"]
description = "All you need to support LNURL and nothing more"
keywords = ["bitcoin", "lightning", "lnurl"]
repository = "https://github.com/lsunsi/lnurl-kit"
license = "GPL-3.0-only"

[dependencies]
